import { Field, ObjectType } from '@nestjs/graphql';

/**
 * This type is used to represent a product in Stripe
 */
@ObjectType()
export class ProductType {
  /**
   * This field is auto generated by Stripe
   * The ID of the product
   */
  @Field(() => String)
  id: string;

  @Field(() => String)
  object: string;

  @Field(() => Boolean)
  active: boolean;

  @Field(() => Number)
  created: number;

  @Field(() => String)
  default_price?: any; // should be a string

  @Field(() => String)
  description: string | null;

  @Field(() => [String])
  images: string[];

  @Field(() => [String])
  marketing_features: any[];

  @Field(() => Boolean)
  livemode: boolean;

  @Field(() => [Object])
  metadata: any;

  @Field(() => String)
  name: string;

  @Field(() => String)
  package_dimensions?: any; // should be a string

  @Field(() => Boolean)
  shippable: boolean | null;

  @Field(() => String)
  statement_descriptor?: string | null;

  @Field(() => String)
  tax_code?: any; // should be a string

  @Field(() => String)
  unit_label?: string | null;

  @Field(() => Number)
  updated: number;

  @Field(() => String)
  url?: string | null;
}
